# Generated by Django 2.0.7 on 2020-04-25 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df_cart', '0002_auto_20200307_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartinfo',
            options={'verbose_name': '的购物车', 'verbose_name_plural': '的购物车'},
        ),
        migrations.AlterField(
            model_name='cartinfo',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_goods.GoodsInfo', verbose_name='商品'),
        ),
    ]
