# Generated by Django 2.0.7 on 2020-03-07 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetailinfo',
            name='count',
            field=models.IntegerField(verbose_name='租数'),
        ),
        migrations.AlterField(
            model_name='orderdetailinfo',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_goods.GoodsInfo', verbose_name='房屋'),
        ),
        migrations.AlterField(
            model_name='orderdetailinfo',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='房屋价格'),
        ),
    ]
