# Generated by Django 2.0.7 on 2020-03-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsinfo',
            options={'verbose_name': '房屋', 'verbose_name_plural': '房屋'},
        ),
        migrations.AlterModelOptions(
            name='typeinfo',
            options={'verbose_name': '房屋类型', 'verbose_name_plural': '房屋类型'},
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='gkucun',
            field=models.IntegerField(default=0, verbose_name='租数'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='gpic',
            field=models.ImageField(blank=True, null=True, upload_to='df_goods/image/%Y/%m', verbose_name='房屋图片'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='gprice',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='房屋单价'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='gtitle',
            field=models.CharField(max_length=20, unique=True, verbose_name='房屋编号'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='gunit',
            field=models.CharField(default='1.2吨', max_length=20, verbose_name='出租单位'),
        ),
    ]
